Pair distribution function
PedestrianDynamics/PedPy pull request #320
Opened 2024-03-28 08:19 UTC by ThoChat

2024-03-29 11:32 UTC, chraibi requested changes
I think you also need to use the formating script before you commit/push

2024-03-29 11:32 UTC, chraibi commented on pedpy/_version.py
is this file necessary?

2024-03-29 11:32 UTC, chraibi commented on pedpy/methods/other_characterisation_methods.py
> +        gdf_f_id = df_f.groupby(ID_COL)
A triple for-loop and twice groupifying?

2024-03-29 11:32 UTC, chraibi commented on pedpy/methods/pair_distribution_function_calculator.py
> +def compute_pair_distibution_function(
is this the same like the other file "other_methods..."

2024-03-29 16:46 UTC, chraibi commented
In general, I'm confused `compute_pair_distibution_function` being in two different files.

2024-04-02 11:21 UTC, schroedtert commented on pedpy/_version.py
This file should not be added to the repo

2024-05-28 13:22 UTC, chraibi commented on pedpy/methods/pair_distribution_function.py
> +        warnings.filterwarnings("default")  # reset wrnings values
warning-values

2024-05-28 13:42 UTC, chraibi approved these changes

2024-05-28 13:43 UTC, chraibi approved these changes

2024-05-28 13:45 UTC, chraibi approved these changes

2024-05-28 13:45 UTC, chraibi submitted a review, later dismissed

2024-05-29 12:45 UTC, schroedtert submitted a review, later dismissed
The new functions are not shown in the API guide on the website

2024-06-04 08:01 UTC, chraibi approved these changes

2024-06-04 08:15 UTC, merged