Add Vadere trajectory loader
PedestrianDynamics/PedPy pull request #382
Opened 2024-09-26 15:54 UTC by gitsimonr

This feature allows users to load trajectory and scenario files that originate from Vadere. The jupyter notebook `user_guide` provides an example. Data for the example and test data are added. Currently, this feature supports data created with Vadere 3.0.

2024-09-28 09:27 UTC, schroedtert commented
Thanks for your contribution, we are really looking forward to support Vadere trajectory files! 
I will try to take a look at your work next week, unfortunately I won't have the time before.

If you have any question or need some assistance, don't hesitate to ask. Especially when our contributing workflow is not clear (you are the first external contributor).

2024-10-02 16:13 UTC, schroedtert requested changes
This looks very good, I just have some points which I want to clarify, before merging this. If you could reply to these remarks, that would be great.

On a different note, you are a bit unfortunate, as we just changed our linting and formatting to ruff. Running the checks locally, yields around 40 places where (mostly minor) remarks are given. If you need any assistance in getting your state to the current main or dealing with the linter warnings just let me know. As I am not that much into the Vadere trajectory format, I'm trusting you, that you kept all the edge cases in mind and handled. And it's great that you added test cases for your changes!

Thanks again for contributing and this great PR. I am hopeful, that we will be able to merge this soon!

2024-10-02 16:13 UTC, schroedtert commented on pedpy/io/trajectory_loader.py
> +    frame_rate: float = 24.0,
IS this the default `frame_rate` in Vadere?

2024-10-02 16:13 UTC, schroedtert commented on pedpy/io/trajectory_loader.py
> +    further analysis and processing in the *PedPy* framework.
In the PR you mention that only Vadere version 3.0 traj files are supported. This should also be mentioned in the documentation. Would it be possible to enforce this? Or what happens with any traj files before 3.0?

2024-10-02 16:13 UTC, schroedtert commented on pedpy/io/trajectory_loader.py
> +                f"Therefore, this trajectory will be ignored."
Do I understand this correctly, when a trajectory is too short to convert from the event-based data to a frame-rate based data, it will be ignored? Is this the intended behavior? 
For me, a single invalid trajectory would render the whole file invalid and the user needs to update their trajectory file. This is the current philosophy of PedPy, if during the reading of the data anything is incorrect, an exception is raised and the user has to correct the data. This way, we make sure, that PedPy does not try to be smarter than the user to avoid any unexpected results when such warning messages get ignored. Or would this workflow not work with Vadere files? 

I'm open to the warnings, but wanted to express my concerns

2024-10-02 16:13 UTC, schroedtert commented on pedpy/io/trajectory_loader.py
> +    """
An alternative approach to deal with the overlapping situation:
Create the walkable area (without obstacles) as `shapely.Polyon` and afterward subtract each of the obstacles from that polygon:
```python
import shapely
import pedpy

outer = shapely.box(-5, -5, 5, 5)
obstacle = shapely.box(-1, -1, 6, 1)

walkable_area_poly = outer.difference(obstacle)
walkable_area = pedpy.WalkableArea(walkable_area_poly)
```

That way, the obstacles could reach to the border and the results may be more accurate

2024-10-02 16:13 UTC, schroedtert commented on pedpy/io/trajectory_loader.py
> +        )
Same as above: Warning vs exception

2024-10-02 16:13 UTC, schroedtert commented on pedpy/io/trajectory_loader.py
> +        data.rename(columns=rename_mapping, inplace=True)
From the ruff linter: PD002 `inplace=True` should be avoided; it has inconsistent behavior

2024-10-02 16:13 UTC, schroedtert commented on pedpy/io/trajectory_loader.py
> +    _supported_types = ["RECTANGLE", "POLYGON"]
Does Vadere currently (or in the near future) support more shape types?

2024-10-02 16:13 UTC, schroedtert commented on tests/unit_tests/io/test_trajectory_loader.py
> +    data["simTime"] = data["simTime"] / frame_rate
Wouldn't this be nan for the default `frame_rate` (=0). If so, is the default=0 really needed?

2024-12-27 17:13 UTC, chraibi commented
@gitsimonr Any updates on this PR? We are preparing the next release and we would love lo have this PR accepted.

2025-01-02 14:04 UTC, gitsimonr commented
> @gitsimonr Any updates on this PR? We are preparing the next release and we would love lo have this PR accepted.

Unfortunately, I was not yet able to continue my work. I'll try to address the requested changes as soon as possible.

2025-07-16 09:38 UTC, chraibi commented
Welcome @﻿Hayato-Hess to this PR! :-)

2025-07-16 13:01 UTC, Hayato-Hess commented on pedpy/io/trajectory_loader.py
> +    frame_rate: float = 24.0,
From what I understand, no. Vadere simulates in 0.4-second intervals. Within each interval, depending on the model, a pedestrian may take multiple steps. The `frame_rate` parameter appears to control the precision of the interpolated steps in the output. A frame rate of 24 frames per second is roughly ten times the simulation frequency of Vadere. I assume the rate was chosen somewhat arbitrarily.

2025-07-16 16:31 UTC, Hayato-Hess commented on pedpy/io/trajectory_loader.py
> +    further analysis and processing in the *PedPy* framework.
I compared the output of a 2.0 .traj file with a 3.0 version. Aside from the actual values, the file structures appear identical. However, reviewing the code reveals a breaking change between versions 1.0 and 1.4. Unfortunately, I wasn’t able to get these older versions running on my machine.

As a workaround, we could check whether all required fields are present in the file. If any are missing, we abort and note that the file may originate from a pre-2.0 version. 

It might be a good idea for vadere to write the vadere version at the beginning of these output files  :thinking:

2025-07-17 08:59 UTC, Hayato-Hess commented on pedpy/io/trajectory_loader.py
> +                f"Therefore, this trajectory will be ignored."
Do I understand this correctly, when a trajectory is too short to convert from the event-based data to a frame-rate based data, it will be ignored?

From what I gather, yes. This would apply when a pedestrian's trajectory duration is less than 0.04 seconds (based on the default `frame_rate`). I suggest we log the time difference between start and end so users can identify and potentially work around the issue by adjusting the frame_rate. Technically, the program could fall back to a lower frame_rate as long as the start and end timestamps are not equal, but this might lead to behavior users don’t expect.

    For me, a single invalid trajectory would render the whole file invalid and the user needs to update their trajectory file. This is the current philosophy of PedPy, if during the reading of the data anything is incorrect, an exception is raised and the user has to correct the data. This way, we make sure, that PedPy does not try to be smarter than the user to avoid any unexpected results when such warning messages get ignored. Or would this workflow not work with Vadere files?

I’m a bit torn on how to handle these warnings versus errors.

On one hand, I fully agree with the current PedPy philosophy: if there’s invalid data, it’s better to raise an exception and force the user to fix it.

On the other hand, this strict approach might disrupt workflows for users who aren’t familiar with the Vadere codebase or don’t have the means to develop tools to clean up their .traj files. For those cases, one possible compromise could be to maintain the current behavior as the default (i.e., fail with an error), but introduce an optional flag like `--ignoreTooShortTrajectories` , which would be mentioned in the exception message to guide users who want to proceed despite the issue. That said, adding flags for this case would increase the program’s complexity.

    Or would this workflow not work with Vadere files?

From my investigation I think this is an edge case so I think it would work with Vadere files in general.

Overall, it makes sense to stick with PedPy’s philosophy. I am open to make the necessary changes.

2025-07-17 09:14 UTC, Hayato-Hess commented on pedpy/io/trajectory_loader.py
> +        )
Personally, I think a warning could be a reasonable solution here. It would inform the user that, given the current `frame_rate`, the results might contain some inaccuracies. This way, the user can decide whether to tolerate the imprecision or adjust the settings accordingly.

To draw a perhaps imperfect analogy. When compressing music, the quality depends on the sampling rate: higher or lower, each has trade-offs. Yet, we still allow users the freedom to choose their preferred rate.

2025-07-17 09:33 UTC, Hayato-Hess commented on pedpy/io/trajectory_loader.py
> +    _supported_types = ["RECTANGLE", "POLYGON"]
Currently, Rectangle and Polygons are supported for obstacles. As of now, there are no plans to add more shape types.

2025-07-17 13:10 UTC, Hayato-Hess commented on tests/unit_tests/io/test_trajectory_loader.py
> +    data["simTime"] = data["simTime"] / frame_rate
I don't think NAN makes a lot of sense for the "simTime". I agree with removing the default value from the `frame_rate`.

2025-07-17 13:21 UTC, Hayato-Hess commented on pedpy/io/trajectory_loader.py
> +        data.rename(columns=rename_mapping, inplace=True)
It appears that there is an ongoing effort within the pandas library to remove inplace support for the rename method (see [PR #51466](https://github.com/pandas-dev/pandas/pull/51466/files/92c6a0a253858405b7a9552eb2bb2cf9fa1fcaf4#diff-f2cc21ad9c9caffa3506c4719e07e1db49a2a3368bd6b41a1abf90eb8e3e416cR11). Although the change is still open for discussion, the use of inplace seems to be quite controversial. 

I suggest replacing this line with:

    data = data.rename(columns=rename_mapping)

2025-07-17 13:45 UTC, Hayato-Hess commented
I spoke with Prof. Dr. Gerta Köster regarding this PR. She pointed out something interesting: since pedestrians in vadere are updated in an event-based manner, it’s possible for their paths to intersect.

That said, such situations are relatively rare in practice, as most pedestrians tend to move in similar directions. 

For example:
- The first person walks from the bottom left to the top right.
- The second person walks from the bottom right to the top left.

Since the persons are updated sequentially, such a move would be considered valid within vadere, even though the paths intersect. Interpolating the paths would cause pedestrians to intersect.

I'm not entirely sure what implications this might have for PedPy.

2025-07-22 18:39 UTC, schroedtert commented on pedpy/io/trajectory_loader.py
> +    frame_rate: float = 24.0,
If there is no actual meaning of a frame rate of 24 in Vadere, I would suggest removing the default value. Do you agree? Thus making it more transparent to the users that this needs to be passed to the function explicitly.

2025-07-22 18:42 UTC, schroedtert commented on pedpy/io/trajectory_loader.py
> +    further analysis and processing in the *PedPy* framework.
Checking for the required fields would be great! Just making everything a little more robust.

From my experience, it is always good to have the versioning of the file structure somewhat present in the files :+1:

2025-07-22 18:45 UTC, schroedtert commented on pedpy/io/trajectory_loader.py
> +        )
Agreed, logging a warning to the users seems to be a suitable solution here

2025-07-22 19:00 UTC, schroedtert commented on pedpy/io/trajectory_loader.py
> +                f"Therefore, this trajectory will be ignored."
Actually, I like your idea of adding a `ignore_too_short_trajectories` parameter to the function. Its default should be 'False`, such that the function raises an error when there are too short trajectories. This should in general be an edge case, as the trajectories need to be really short to not be included in a reasonable frame rate. When the trajectory is ignored, I would still suggest printing a warning, making it visible to the user that some trajectory is ignored. 

I am not sure if feasible, but I think it would be great that in case of too short trajectory, a list with all trajectories that are too short is displayed together with a frame rate where they would be included. E.g.,
> Trajectory of pedestrians 1 (0.1s), 5 (0.2s), 8 (0.1s) are too short in time to be captured by the chosen frame rate of 25. To include these trajectories in the data please chose a frame rate of at least 50 or to ignore these trajectories set `ignore_too_short_trajectories=True`.

Just to sum up my preferred approach, if you have any points you disagree with, let me know. 

- add parameter `ignore_too_short_trajectories=False` to `load_trajectory_from_vadere`
- if `ignore_too_short_trajectories=False`:
  - raise errors when trajectories are to short. The error message should show a proposed frame rate, that would include the trajectory
- if `ignore_too_short_trajectories=True`:
  - ignore too short trajectories, but display a warning like: Trajectory X is ignored for frame rate Y

2025-07-22 19:06 UTC, schroedtert commented
Hi @Hayato-Hess, 
thanks taking over this PR and for your feedback on my points. I really appreciate it and hope we will get this merged soon! 

As this PR has been open for quite a while, there might be some/more merge conflicts. And as I pointed out before, we switched to ruff as linter shortly before this PR got opened. Meanwhile, we set the linting/formatting up as pre-commit hooks. as described in our [Developer Guide](https://pedpy.readthedocs.io/stable/developer_guide.html#formatting-linting). If you need any assistance or anything is unclear, just let us know and we'll try to help you.

2025-07-23 07:09 UTC, chraibi commented on pedpy/io/trajectory_loader.py
> +    frame_rate: float = 24.0,
@Hayato-Hess I suggest to not pass any default values here. This might be changed in vadere. 
If you can't change it, I can try to force-push some changes here.

2025-07-23 07:20 UTC, chraibi commented
> I spoke with Prof. Dr. Gerta Köster regarding this PR. She pointed out something interesting: since pedestrians in vadere are updated in an event-based manner, it’s possible for their paths to intersect.
> 
> That said, such situations are relatively rare in practice, as most pedestrians tend to move in similar directions.
> 
> For example:
> 
>     * The first person walks from the bottom left to the top right.
> 
>     * The second person walks from the bottom right to the top left.
> 
> 
> Since the persons are updated sequentially, such a move would be considered valid within vadere, even though the paths intersect. Interpolating the paths would cause pedestrians to intersect.
> 
> I'm not entirely sure what implications this might have for PedPy.

Since it's a rare event, I would just accept the risk. Just finish up this PR. In the future, if some vadere-user is stuck in this situation, then we can look into the "bug".

2025-07-30 12:31 UTC, Hayato-Hess commented on pedpy/io/trajectory_loader.py
> +    frame_rate: float = 24.0,
I agree not to pass a default value. 

@chraibi I can not change the PR. See if you can force-push the changes. Otherwise I could also create a new PR.

2025-07-30 12:46 UTC, Hayato-Hess commented
@chraibi I'm unable to make changes to this PR. I could create a new branch with the changes we discussed above. We could then try to force-push the changes into this PR. If this doesn't work I could also open a new PR.

2025-07-31 11:28 UTC, chraibi commented
> @chraibi I'm unable to make changes to this PR. I could create a new branch with the changes we discussed above. We could then try to force-push the changes into this PR. If this doesn't work I could also open a new PR.

Is it maybe better to clone this branch and base your work on it?

2025-08-04 12:43 UTC, Hayato-Hess commented on pedpy/io/trajectory_loader.py
> +    further analysis and processing in the *PedPy* framework.
I noticed that an error message for missing fields is already in place:
https://github.com/PedestrianDynamics/PedPy/pull/382/files/40800a90f21cbe11fa1ce6ced03d4c3905a9d59e#diff-f8408bffe4719804c18600918d9c725bb38ce03f631aee71166e14e7ba493995R737

I'll update the message to also suggest that the issue might be due to using an outdated Vadere version used for the export.

2025-08-04 14:57 UTC, Hayato-Hess commented
@chraibi I created a draft PR https://github.com/Hayato-Hess/PedPy/pull/2 with the discussed changes. I hope you can grab the changes from there and force push them.

@schroedtert It would be great if you could check if the changes in https://github.com/Hayato-Hess/PedPy/commit/8b465a6d75a0e7762d3d4173f18bc756a1d3ee3b are what you envisioned

2025-08-04 17:37 UTC, chraibi commented
Hi Hayato,
this looks great already. However, could you please create a PR in this repository instead?

2025-08-05 19:08 UTC, schroedtert commented
Superseded by #460

2025-08-05 19:08 UTC, closed without merging