Git hooks
PedestrianDynamics/PedPy pull request #387
Opened 2024-09-30 11:55 UTC by chraibi

With [pre-commit](https://pre-commit.com/) we can check if everything is well formated and mypy-checked before committing:
`
pre-commit run --all-files
`

2024-09-30 18:02 UTC, schroedtert requested changes
I played with the idea of using pre-commit, nice that you did it!

But, then we also need to update the following:

- Dev Guide: How to set up and use it
- The CI script then should also use pre-commit. Otherwise, we have the same thing in two places, which is always bad

2024-09-30 18:02 UTC, schroedtert commented on .pre-commit-config.yaml
> +        exclude: (tests/|scripts/)
newline at the end is missing

2024-09-30 18:02 UTC, schroedtert commented on requirements.txt
> +pre-commit
```suggestion
pre-commit~=3.8
```

This way, we make sure to only use versions compatible with 3.8 (assuming you used the latest available version)

2024-09-30 23:29 UTC, chraibi commented
> The CI script then should also use pre-commit. Otherwise, we have the same thing in two places, which is always bad

Yes, that is necessary. The pre-commit basically copies all checks of the ci. 
I don't want to mess up with Ci, though ^^

2024-10-01 06:39 UTC, schroedtert commented
I can have a look and do it, if you want.

2024-10-01 10:02 UTC, chraibi commented
> I can have a look and do it, if you want.

Sure! That would be nice!

2024-10-08 18:04 UTC, schroedtert commented
@chraibi I updated some stuff, what do you think? Is it okay for you or is anything missing?

2024-10-08 18:04 UTC, schroedtert approved these changes

2024-10-08 23:19 UTC, chraibi commented
> @chraibi I updated some stuff, what do you think? Is it okay for you or is anything missing?

Looks nice!

2024-10-12 10:33 UTC, merged